name: Delete responses
run-name: ${{ github.actor }} is deleting responses
on:
  workflow_dispatch: # Trigger job manually
  schedule:
  - cron: "*/5 * * * *" # Trigger job every five minutes
jobs:
  delete-responses-job:
    runs-on: ubuntu-latest  
    steps:
      - run: echo "Job was triggered by event ${{ github.event_name }}"
      - uses: actions/github-script@v7
        env:
          TYPEFORM_API_TOKEN: ${{ secrets.TYPEFORM_API_TOKEN }}
        with:
          script: |
            const { TYPEFORM_API_TOKEN } = process.env
            console.log(`Hello ${TYPEFORM_API_TOKEN}`)

            const res = await fetch('https://jsonplaceholder.typicode.com/users');
            console.log({ res });

            const users = await res.json();

            console.log({ users });
