name: Delete responses
run-name: ${{ github.actor }} is deleting responses
on:
  workflow_dispatch: # Trigger job manually
  schedule:
  - cron: "*/5 * * * *" # Trigger job every five minutes
jobs:
  delete-responses-job:
    runs-on: ubuntu-latest  
    steps:
      - run: echo "Job was triggered by event ${{ github.event_name }}"
      - uses: actions/github-script@v7
        env:
          TYPEFORM_API_TOKEN: ${{ secrets.TYPEFORM_API_TOKEN }}
          TYPEFORM_FORM_ID: "hwau3Ssv"
        with:
          script: |
            const { TYPEFORM_API_TOKEN, TYPEFORM_FORM_ID } = process.env
            console.log(`Hello ${TYPEFORM_API_TOKEN}`)

            const url = `https://api.typeform.com/forms/${TYPEFORM_FORM_ID}/responses`;
            const headers = { 'Authorization': `Bearer ${TYPEFORM_API_TOKEN}` };            
            const res = await fetch(url, { headers });
            const stuff = await res.json();
            console.log({ stuff });

            
