name: Delete responses
run-name: ${{ github.actor }} is deleting responses
on:
  workflow_dispatch: # Trigger job manually
  schedule:
  - cron: "*/5 * * * *" # Trigger job every five minutes
jobs:
  delete-responses-job:
    runs-on: ubuntu-latest  
    steps:
      - run: echo "Job was triggered by event ${{ github.event_name }}"
      - uses: actions/github-script@v7
        env:
          TYPEFORM_API_TOKEN: ${{ secrets.TYPEFORM_API_TOKEN }}
          TYPEFORM_FORM_ID: "hwau3Ssv"
        with:
          script: |
            const { TYPEFORM_API_TOKEN, TYPEFORM_FORM_ID } = process.env
            const responsesUrl = `https://api.typeform.com/forms/${TYPEFORM_FORM_ID}/responses`

            // Get up to 1000 completed or partial responses
            const getUrl = `${responsesUrl}?page_size=1000&response_type=partial,completed`;
            const getHeaders = { 'Authorization': `Bearer ${TYPEFORM_API_TOKEN}`};            
            const getOptions = { headers: getHeaders }
            const getRes = await fetch(getUrl, { getOptions });
            const getJson = await getRes.json();
            const { items } = getJson;

            // Extract the response ids
            const response_ids = items.map(item => item.response_id);

            console.log({ response_ids })

            // Delete responses
            const deleteUrl = responsesUrl;
            

            
