name: Delete responses
run-name: ${{ github.actor }} is deleting responses
on: []
jobs:
  delete-responses-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job was triggered by event ${{ github.event_name }}"
