name: Delete responses
run-name: ${{ github.actor }} is deleting responses
on:
  workflow_dispatch: # Trigger job manually
  schedule:
  - cron: "*/5 * * * *" # Trigger job every five minutes
jobs:
  delete-responses-job:
    runs-on: ubuntu-latest  
    steps:
      - run: echo "Job was triggered by event ${{ github.event_name }}"
      - uses: actions/github-script@v7
        env:
          TYPEFORM_API_TOKEN: HELLOTOKEN
        with:          
          script: |
            const { TYPEFORM_API_TOKEN } = process.env
            console.log('Hello Typeform.');
            console.log('Hello ${TYPEFORM_API_TOKEN} `)
  
