name: Delete responses
run-name: ${{ github.actor }} is deleting responses
on:
  workflow_dispatch: # Trigger job manually
  schedule:
  - cron: "13 5 * * 0" # Trigger job weekly on at 05:13 on Sundays
jobs:
  delete-responses-job:
    runs-on: ubuntu-latest  
    steps:
      - run: echo "Job was triggered by event ${{ github.event_name }}"
      - uses: actions/github-script@v7
        env:
          TYPEFORM_API_TOKEN: ${{ secrets.TYPEFORM_API_TOKEN }}
          TYPEFORM_FORM_ID: "aUN6GIR4"
        with:
          script: |
            const { TYPEFORM_API_TOKEN, TYPEFORM_FORM_ID } = process.env
            const responsesUrl = `https://api.typeform.com/forms/${TYPEFORM_FORM_ID}/responses`
            const headers = { 'Authorization': `Bearer ${TYPEFORM_API_TOKEN}`};            

            // Get up to 1000 completed or partial responses
            const getUrl = `${responsesUrl}?page_size=1000&response_type=partial,completed`;            
            const getOptions = { headers }
            const getRes = await fetch(getUrl, getOptions);            
            const { status: getStatus } = getRes;            
            console.log({ getStatus })

            // Extract the response ids
            const getJson = await getRes.json();            
            const { items } = getJson;
            const response_ids = items.map(item => item.response_id);
            console.log({ response_ids })

            // Delete responses
            const deleteUrl = responsesUrl;        
            const bodyData = {
              included_response_ids: response_ids
            };
            const deleteOptions = {
              method: "DELETE",
              headers,
              body: JSON.stringify(bodyData)
            };
            const deleteRes = await fetch(deleteUrl, deleteOptions);
            const { status: deleteStatus } = deleteRes;            
            console.log({ deleteStatus })
            
            
            

            
